### ISSUE TITLE
Suggestion: Right-Click to Have Journal Element Read Aloud

### ISSUE THREAD

**Issue by Armandeus66** [acd-jake/acd-talking-actors#22]
I really like the inclusion of journal narration in this module, and also the integration with other scene conversation modules!

I would like to suggest that in addition to a macro, perhaps there could be a right-click menu that would read selected text from a journal using the Narrating Actor setting for this module.

As an example of a module that uses a right-click menu to send selected journal text to chat or the center of the screen, please have a look at Narrator Tools.
https://github.com/elizeuangelo/fvtt-module-narrator-tools

One advantage of a context menu over pre-inserting a macro into the journal is that you could have something read aloud that you did not think to prepare for beforehand by inserting the macro, like a rules paragraph that answers a question during play.

Thanks for updating and adding things to Talking Actors! It is not only lots of fun, but it saves the GM (me!) from having to read long descriptions to the players myself. Thank you, Acd-Jake!

**Comment by aeonxan** [comment]
Second this! Would be nifty for GM note or preplanned voice lines organization.

**Comment by acd-jake** [comment]
Hello,

from the next version (probably version 0.7) it will be possible to have the selected text in a journal entry read aloud using a context menu. You can choose whether the text should be read out with the voice of the narrator or whether it should be spoken by the active actor.

![image](https://github.com/acd-jake/acd-talking-actors/assets/67855941/d8fd4b44-4a59-4cc7-8bc3-6656d7de9b48)

Does this correspond to the enhancements you have suggested?

**Comment by Armandeus66** [comment]
Yes, thanks! That would be great. I'm looking forward to it!
(Will it work together with the Narrator module's right-click context menu without conflicting?)

**Comment by acd-jake** [comment]
Hi,

unfortunately, there is no way to extend the context menu of the Narrator module. This option is not provided in the Narrator module.

Therefore, I only have the option of creating and displaying a context menu myself. I have now implemented this.

This means it will not work together with the Narrator module without conflicts.

To compensate for this at least a little, you can enable or disable the context menu for the speech output via the module settings.

A permanent solution would be to implement another module that offers expandable context menus for the selected text in journal entries, into which other modules such as Talking Actors or the Narrator module can then be hooked.

However, I would be reluctant to implement this directly within Talking Actors, as the other modules would then be dependent on it, even if they do not require the speech output functionality.
