### ISSUE TITLE
Question about Chat Replay

### ISSUE THREAD

**Issue by Armandeus66** [acd-jake/acd-talking-actors#23]
Does the chat replay function retain and replay the generated audio within Foundry, or does it ask Elevenlabs to regenerate it, which would count against the word limit and might be vocalized a bit differently?

**Comment by acd-jake** [comment]
The playback function does **not** regenerate the spoken text and therefore does **not** count against the character limit of the Elevenlab account. 

Instead, the module uses the history of generated samples in Elevenlabs and loads the corresponding sample to play it back. The sample will therefore be pronounced the same each time, even if it is not stored in the Foundry itself.

Does this answer your question?

**Comment by Armandeus66** [comment]
Thank you, it does.

2024年1月26日(金) 3:26 acd-jake ***@***.***>:
