### ISSUE TITLE
Question about the Narrator Actor

### ISSUE THREAD

**Issue by Armandeus66** [acd-jake/acd-talking-actors#24]
Can the Narrator Actor be used to /talk without selecting a token (it gives me an error saying no Elevenlabs voice selected)? 

I can talk without a token if I use /talk [VoiceName], but I thought the Narrator Actor might be useful here, especially if this were limited to use by the GM.

**Comment by acd-jake** [comment]
I have just tried it out with version 0.6 without any problems.

I have stored the Api key and the ID of the narrating actor in the settings. Then I used the "/talk" command without a selected token and without any other parameters. The text was spoken correctly with the voice of the narrating actor.

Which version of the module are you using?

**Comment by acd-jake** [comment]
The "Narrating Actor (ID)" setting has to be the foundry id of the actor that will serve as the narrator. The id can be aquired in foundry by clicking on the icon next to the actor name in the title of the character sheet in foundry.

![image](https://github.com/acd-jake/acd-talking-actors/assets/67855941/9c7287b5-3c69-47c1-95df-a4153eee717b)

**Comment by Armandeus66** [comment]
Thank you for explaining with a screenshot!

I'm not sure I understand, though. The narrator voice is not the GM as narrator, but instead an actor?

Is that actor dependent on being in a scene or not? If not, how do you assign it a voice? If you have to do it by scene, how is it a "default" voice across scenes?

I guess I misunderstood. I thought the narrator was meant to be the GM voice (for reading room descriptions or rules). What was your intention?

**Comment by acd-jake** [comment]
Hello,

the settings for the voices are stored within the actors, which makes it possible for an actor to have the same voice modulation in every scene.

Therefore, it was easiest to simply add the option to declare one of these actors as the narrating actor.

This actor then only has to be placed in a scene to make the voice settings and can then be removed from the scene again. 

So to create a "narrator", you can simply create an actor for it, ideally with the name "narrator". You then place it in a scene, make the voice settings and remove it again.

From now on, you can use the command "`/talk [narrator] ...`" to have the narrator speak at any time - even if no scene is open at all.

Is it easier to understand now?

**Comment by Armandeus66** [comment]
Sorry I'm late to respond.

I now understand that you are storing some variables for voices in actor sheets, and that's why you need an actor for the narrator.

My constructive criticism of that would be, it seems to be a lot of work to have to put the narrator actor into every scene, for an actor that the players will never see.

If II may, I would like to offer two suggestions.

1) Put the narrator actor's parameters into the Foundry settings dialog instead of attaching it to an actor.

2) Add a setting for an optional narrator voice (designated in the settings) that has no settings to be saved in an actor, but can be used as the default GM voice for reading rules, dungeon descriptions, and so on.

The advantage to doing either of those would be, the GM would not need to tie his/her narrator "voice" to a scene, saving the GM from having to setup that actor for all scenes, and, if you decided to add right-click context menu narration from a journal, the voice could be the default for that, again not needing to be setup for each scene.

I see why you put the voice parameters in the actor sheets, because that's mostly where they are needed, but I feel that I can give up on the parameters for narrator, for the sake of the convenience of not having to set it up per scene, because as the GM, the narrator seems intuitively unrelated to the scene.

Those are only suggestions, of course. Sorry for the long post, and thanks for making the module. I am very glad you did.

**Comment by acd-jake** [comment]
Hi, 

sorry for the late reply, I'm currently having problems with my internet access.

I may have misunderstood, but the voice settings for the actors are not linked to the scenes. That's exactly the reason why these settings are stored in the actors themselves.

The procedure is as follows and is only required for the actual configuration of the voice.

1. you create an actor.
2. this actor is placed in any scene and the voice settings for the actor are made.
3. the settings are now saved in the actor and it can be removed from the scene again.

Regardless of whether the actor is now in a scene or not, the /talk command can now be used for it and its voice settings apply to the spoken texts.

The voice settings are therefore not tied to the scenes in any way.

You can now place the actor in a different scene or not, in fact it no longer plays a role in speech generation. Only the pan on the token and the speech bubble only occur when the actor is in the current scene.

Is it easier to understand now?

**Comment by Armandeus66** [comment]
Thanks for explaining everything!

I was confused about scenes because you have to put an actor-linked token on a scene to assign or edit a voice. I suppose I would not have misunderstood if there was a setting on the actor sheet itself (a tab in the assign token settings, maybe?) for that instead. 

Sorry.

**Comment by acd-jake** [comment]
Hello,

from the next version (probably version 0.7) it will be possible to open the window for the voice settings directly from the title bar of the actor sheet. There will also be a corresponding button in the context menu of the actors in the actor folder.

Perhaps this will make it more intuitive to use.

The button in the scene control can still be used to set the voices of several actors via their tokens.

The wiki is already in progress.

Would that help you?

**Comment by bookguysmith** [comment]
Yes, this is fantastic news.

**Comment by Armandeus66** [comment]
Thanks for looking into this and making it easier to understand! I really appreciate it!
