### ISSUE TITLE
Add enrichers for journals to read aloud sections of text

### ISSUE THREAD

**Issue by acd-jake** [acd-jake/acd-talking-actors#30]
In the texts of the journals, enrichers should be added to read sections of the text aloud.

This would allow the relevant passages to be highlighted visually and sent to the chat and read aloud when clicked.

Example when editing a journal entry:
![image](https://github.com/acd-jake/acd-talking-actors/assets/67855941/18492262-3f18-45b9-90cf-0e654a2867bf)

Example when viewing the journal entry:
![image](https://github.com/acd-jake/acd-talking-actors/assets/67855941/699fcf6b-74a2-47d2-8e4f-223b021a2933)

Clicking on the speech bubble on the right border of the title for the passage will read aloud the content and send it to the chat.

**Comment by Armandeus66** [comment]
This is great! Thank you!
