### ISSUE TITLE
Not seeing where to configure voices

### ISSUE THREAD

**Issue by BenTheCloudGuy** [acd-jake/acd-talking-actors#31]
Perhaps I'm just missing it, but I'm not seeing where I configure the voices for the Actors in FoundryVTT after enabling the module and setting my API key for ElevenLabs. Does this work with all systems\character sheets?

**Comment by acd-jake** [comment]
Hello,

in the current version (0.6) you have to place the actor whose voice you want to configure in the scene and select the resulting token. Then you can open the window for the voice settings via the corresponding button in the left bar.

The token can then be removed from the scene, as the settings are saved in the actor itself.

From the upcoming version 0.7, it will no longer be necessary to go via the token in the scene.

In that version it will be possible to open the window for the voice settings directly from the title bar of the actor sheet. There will also be a corresponding button in the context menu of the actors in the actor folder.

I will release the version 0.7. in the next days.

Does this answer your question?

**Comment by acd-jake** [comment]
No further activity needed.
