### ISSUE TITLE
Feature-Request: Audio Only - no text in chat

### ISSUE THREAD

**Issue by haho76** [acd-jake/acd-talking-actors#33]
Hi, would it be possible to have a setting that would prevent text from showing in chat, but only generate/play audio?
Reason is: I use that (great module btw!) mainly for the text in official adventures that should be read to the players....
It works great...but it takes  a couple of seconds before audio starts playing and so players already read ahead in chat, which breaks immersion.

**Comment by acd-jake** [comment]
Hello, 

First of all, thank you very much for the praise.

I think your idea is really good and useful.

Would it make more sense to make this functionality generally adjustable via a configuration setting or should it be selectable for individual voice commands?

Both probably make sense. I will therefore extend the configuration accordingly in the next release and also add the chat command "talks" for stealthy speaking, i.e. voice output without text output in the chat. 

If you have a suggestion for a better name for the new chat command, please let me know.
