### ISSUE TITLE
Feature Request: Elevenlabs Sound Effects

### ISSUE THREAD

**Issue by Armandeus66** [acd-jake/acd-talking-actors#35]
This is one of my favorite modules. Thanks for making it!

Would you consider a feature to use the Elevenlabs API to also create sound effects? This feature was recently added to Elevenlabs.

Maybe generating the sounds through the Foundry playlist interface, rather than based on actors, might be best. The generated sounds could be saved to a designated folder and then accessed through the playlist, or used in other ways like on scenes or tokens.

There is another Elevenlabs module for foundry that covers this (VoiceGen), but using both that and your module would double up on the text to speech interface, and I prefer the interface of your module.

**Comment by acd-jake** [comment]
Hi,

that's an interesting suggestion, this feature from ElevenLabs was actually new to me.

I'll have a look at what the API has to offer and think about how I can add this functionality to the Talking Actors module.

I certainly like your suggestion with the playlists and the designated folder.
