### ISSUE TITLE
Make API key setting to optionally be a global one (Was Allowing Players to /talk)

### ISSUE THREAD

**Issue by Armandeus66** [acd-jake/acd-talking-actors#4]
The module works fine for the GM to have NPC actors (token with actor linked and set with module button for scene in left menu), but when I set it up for PC controlled actors in the same way, voices are not played at all for GM or PC.

**Comment by acd-jake** [comment]
Hi,

the module does not differentiate between NPCs and PCs. As long as an actor is connected to the token, the voices are played. The GM can have any actor speak, he just has to be able to impersonate him. A PC can only let actors speak over which he has control.

The only restriction is that the Elevenlabs API key must be stored in the settings of the account through which the voices are to be played with the /talk command.

This means that if both a player and the game master use the module to have their respective characters speak, both the game master and the player must store their API keys in the settings. However, this can also be the same API key, which is simply saved by both parties.

I have just tried this again for NPCs and PCs both as the GM and a player and it worked without any problems. 

If it doesn't work for you, do you have any further information for me? Are errors displayed in the debug console?

**Comment by Armandeus66** [comment]
"The only restriction is that the Elevenlabs API key must be stored in the settings of the account through which the voices are to be played with the /talk command."

If I have a token with linked actor talk, players hear it. If a player does it, nobody hears it.

Are you saying that the API key input on the GM's end is not a global setting and so all players who will use the function of the module must also have an API key (or the same one) input into their client settings?

Would it be possible for the API key setting to optionally be a global one?

**Comment by acd-jake** [comment]
> Are you saying that the API key input on the GM's end is not a global setting and so all players who will use the function of the module must also have an API key (or the same one) input into their client settings?

Yes, this is currently implemented in this way.

> Would it be possible for the API key setting to optionally be a global one?

I'll take this as a suggestion for enhancement and will try to implement it in the next release.
