### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by MastaGooz** [acd-jake/acd-talking-actors#6]
Hi, 

When I try to use the talking actor, I get a Foundry alert "/talk is not a valid command", and I get this error in the console.
![image](https://github.com/acd-jake/acd-talking-actors/assets/149971487/b941b23e-1e9e-4386-b65d-2f2c135f7958)

I don't know if I'm using the module correctly, I put the API key and set a voice to the token.
But the chat talk is not working.

**Comment by acd-jake** [comment]
Hi,

can you give me some more information about the environment in which you are using the module?

In particular, it would be interesting to know which system you are using it under and whether the problem also occurs if you are not using any other modules.

Then I can try to recreate the problem and fix it.

**Comment by acd-jake** [comment]
Hi, I just fixed an error in the actor retrieval. Please check if your issue has been resolved by the [release 0.4.2](https://github.com/acd-jake/acd-talking-actors/releases/tag/0.4.2)

**Comment by MastaGooz** [comment]
Yes, it is fixed, thanks !
